#!/bin/sh

if [ "$JAVA_HOME" == "" ]
then
    echo "NO JAVA_HOME SET"; exit 1
fi

#
# Compile LabSAT solver
#
mvn package
mv target/LabSAT-0.0.1-jar-with-dependencies.jar solver.jar

#
# Compile lingeling SAT-solver as shared library
#
cd lib/lingeling/code
chmod 755 configure.sh mkconfig.sh
./configure.sh -fPIC
make lingeling
cd ../../..

#
# Compile JNI for LabSAT <-> lingeling
#
cd lib
gcc -I $JAVA_HOME/lib/ -I $JAVA_HOME/include/ -I $JAVA_HOME/include/linux/ \
-o libLingeling.so argumentation_sat_Lingeling.c -L./lingeling/code -llgl -fPIC -shared
mv libLingeling.so ..
cd ..

chmod 755 solver
