/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class argumentation_sat_Lingeling */

#ifndef _Included_argumentation_sat_Lingeling
#define _Included_argumentation_sat_Lingeling
#ifdef __cplusplus
extern "C" {
#endif
#undef argumentation_sat_Lingeling_UNKNOWN
#define argumentation_sat_Lingeling_UNKNOWN 0L
#undef argumentation_sat_Lingeling_SATISFIABLE
#define argumentation_sat_Lingeling_SATISFIABLE 10L
#undef argumentation_sat_Lingeling_UNSATISFIABLE
#define argumentation_sat_Lingeling_UNSATISFIABLE 20L
/*
 * Class:     argumentation_sat_Lingeling
 * Method:    lglinit
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_argumentation_sat_Ligeling_lglinit
  (JNIEnv *, jobject);

/*
 * Class:     argumentation_sat_Lingeling
 * Method:    lglclone
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_argumentation_sat_Lingeling_lglclone
  (JNIEnv *, jobject, jlong);

/*
 * Class:     argumentation_sat_Lingeling
 * Method:    lglrelease
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_argumentation_sat_Lingeling_lglrelease
  (JNIEnv *, jobject, jlong);

/*
 * Class:     argumentation_sat_Lingeling
 * Method:    lglderef
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_argumentation_sat_Lingeling_lglderef
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     argumentation_sat_Lingeling
 * Method:    lgladd
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_argumentation_sat_Lingeling_lgladd
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     argumentation_sat_Lingeling
 * Method:    lglsat
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_argumentation_sat_Lingeling_lglsat
  (JNIEnv *, jobject, jlong);

/*
 * Class:     argumentation_sat_Lingeling
 * Method:    lglfreeze
 * Signature: (JI)I
 */
JNIEXPORT void JNICALL Java_argumentation_sat_Lingeling_lglfreeze
  (JNIEnv *, jobject, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
